---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  eslint:
    enabled: true
  nodesecurity:
    enabled: true
  requiresafe:
    enabled: true
ratings:
  paths:
  - "**.js"
exclude_paths: ['.idea', 'coverage','Gruntfile.js']
